name: Update requirements.txt and package.json

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Change this to the Python version you're using

    - name: Install Python dependencies
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        TWILIO: ${{ secrets.TWILIO }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Update requirements.txt
      run: |
        pip freeze > requirements.txt

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '19'  # Change this to the Node.js version you're using

    - name: Install Node.js dependencies
      run: |
        if [ -f package.json ]; then npm install; fi

    - name: Update package.json
      run: |
        npm update

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update dependencies"
        title: "Update dependencies"
        branch: "update-dependencies"
