name: python

on: push

jobs:
  test_env:
    environment: PROJECT_SECRET
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        TWILIO: ${{ secrets.TWILIO }}
